[project]
name = "backend"
version = "0.1.0"
description = "Backend for schemazz"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.127.0",
    "supabase>=2.27.0",
]
